### ISSUE TITLE
setup-script is not invoked when building sdists

### ISSUE THREAD

**Issue by jauerb** [pdm-project/pdm-pep517#117]
Custom setup scripts as described https://pdm.fming.dev/latest/pyproject/build/#custom-file-generation are only invoked when building wheels, not when building sdists.

I am not sure if that is intentional, but I am looking for a way to invoke a custom script for all builds, and there does not seem to be a way to invoke a custom script when building sdists.

**Comment by frostming** [comment]
Try the new rewritten `pdm-backend`, change the build config to the following:

```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```
